# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Pengfei Zhang'
tagline:          'Pengfei'
description:      '<p>Undergraduate<br>School of Computer Science, University of Science and Technology of China (USTC), Hefei, China.</p>
                   <p><a href="mailto:zpf0117b@mail.ustc.edu.cn">zpf0117b@mail.ustc.edu.cn</a></p>'
url:              http://zpf0117b.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme:            jekyll-theme-minimal
