# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Pengfei Zhang'
tagline:          ''
description:      '<p>Senior Undergraduate Student<br>School of Computer Science,University of Science and Technology of China,Hefei, Anhui.</p>
                   <p><a href="mailto:service@test.com">zpf0117b@mail.ustc.edu.cn</a></p>'
url:              http://zpf0117b.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
